# Generated by Django 6.0.3 on 2026-03-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Eshik nomi')),
                ('brand', models.CharField(max_length=100, verbose_name='Brend')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Narxi (UZS)')),
                ('category', models.CharField(choices=[('Standart', 'Standart'), ('Premium', 'Premium')], default='Standart', max_length=50)),
                ('image', models.ImageField(upload_to='dooors/', verbose_name='Eshik rasmi')),
                ('coating', models.CharField(max_length=100, verbose_name='Qoplama')),
                ('structure', models.CharField(max_length=100, verbose_name='Tuzilishi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
            ],
            options={
                'verbose_name': 'Eshik',
                'verbose_name_plural': 'Eshiklar',
            },
        ),
    ]
