# Generated by Django 6.0.2 on 2026-03-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='price',
            field=models.IntegerField(verbose_name='Narxi (UZS)'),
        ),
    ]
